version: "3.9"

services:
  db:
    image: postgres:15
    container_name: books-db-new
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - books-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: books-redis
    ports:
      - "6379:6379"

  books-service:
    build: .
    container_name: books-service
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8002:8002"
    command: >
      sh -c "python init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload"

volumes:
  books-data:
